// leetcode generates test adapters from Go signatures, then runs shared fixtures.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/ericliutech/leetcode/internal/judge"
)

const generatedName = "zz_generated_test.go"
const generatedHeader = "// Code generated by leetcode; DO NOT EDIT."

type entry struct {
	name       string
	parameters []string
}

func discoverEntry(directory string, keys []string, selected string) (string, entry, error) {
	files, err := os.ReadDir(directory)
	if err != nil {
		return "", entry{}, err
	}
	var packageName string
	var candidates []entry
	for _, file := range files {
		if file.IsDir() || !strings.HasSuffix(file.Name(), ".go") || strings.HasSuffix(file.Name(), "_test.go") {
			continue
		}
		source, err := parser.ParseFile(token.NewFileSet(), filepath.Join(directory, file.Name()), nil, 0)
		if err != nil {
			return "", entry{}, err
		}
		if packageName != "" && packageName != source.Name.Name {
			return "", entry{}, fmt.Errorf("mixed Go packages in %s", directory)
		}
		packageName = source.Name.Name
		for _, declaration := range source.Decls {
			function, ok := declaration.(*ast.FuncDecl)
			if !ok || function.Recv != nil || function.Name.Name == "init" || function.Name.Name == "main" {
				continue
			}
			if selected != "" && function.Name.Name != selected {
				continue
			}
			if function.Type.TypeParams != nil || function.Type.Results == nil || function.Type.Results.NumFields() != 1 {
				continue
			}
			candidate := entry{name: function.Name.Name}
			supported := true
			for _, parameter := range function.Type.Params.List {
				if _, variadic := parameter.Type.(*ast.Ellipsis); variadic || len(parameter.Names) == 0 {
					supported = false
				}
				for _, name := range parameter.Names {
					if name.Name == "_" {
						supported = false
					}
					candidate.parameters = append(candidate.parameters, name.Name)
				}
			}
			actual := append([]string(nil), candidate.parameters...)
			sort.Strings(actual)
			if supported && strings.Join(actual, "\x00") == strings.Join(keys, "\x00") {
				candidates = append(candidates, candidate)
			}
		}
	}
	if len(candidates) == 0 {
		return "", entry{}, fmt.Errorf("%s: no function matches input keys %v with fixed named parameters and one result", directory, keys)
	}
	if len(candidates) != 1 {
		names := make([]string, len(candidates))
		for index, candidate := range candidates {
			names[index] = candidate.name
		}
		return "", entry{}, fmt.Errorf("%s: ambiguous entry functions %v; use --function with one solution directory", directory, names)
	}
	return packageName, candidates[0], nil
}

func renderAdapter(packageName string, function entry, fixtures, comparison string) ([]byte, error) {
	var output bytes.Buffer
	fmt.Fprintf(&output, "%s\npackage %s\n\nimport (\"testing\"; \"github.com/ericliutech/leetcode/internal/judge\")\n", generatedHeader, packageName)
	fmt.Fprintf(&output, "func TestSolution(t *testing.T) { judge.Run(t, %s, %s, []string{", strconv.Quote(filepath.ToSlash(fixtures)), function.name)
	for _, name := range function.parameters {
		fmt.Fprintf(&output, "%s,", strconv.Quote(name))
	}
	fmt.Fprintf(&output, "}, %s) }\n", strconv.Quote(comparison))
	return format.Source(output.Bytes())
}

func problemFor(directory, root string) (string, error) {
	for path := directory; path != root; path = filepath.Dir(path) {
		if _, err := os.Stat(filepath.Join(path, "testcases.json")); err == nil {
			return path, nil
		}
	}
	return "", fmt.Errorf("%s: no parent problem with testcases.json", directory)
}

var comparisonLine = regexp.MustCompile(`(?m)^Comparison:[ \t]*(.*)$`)

func prepare(root, directory, selected string) (string, []byte, error) {
	problem, err := problemFor(directory, root)
	if err != nil {
		return "", nil, err
	}
	cases, err := judge.Load(filepath.Join(problem, "testcases.json"))
	if err != nil {
		return "", nil, err
	}
	keys := make([]string, 0, len(cases[0].Input))
	for key := range cases[0].Input {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	packageName, function, err := discoverEntry(directory, keys, selected)
	if err != nil {
		return "", nil, err
	}
	statement, err := os.ReadFile(filepath.Join(problem, "problem.md"))
	if err != nil {
		return "", nil, err
	}
	comparison := "exact"
	settings := comparisonLine.FindAllSubmatch(statement, -1)
	if len(settings) > 1 {
		return "", nil, fmt.Errorf("%s: duplicate Comparison setting", problem)
	}
	if len(settings) == 1 {
		comparison = strings.TrimSpace(string(settings[0][1]))
	}
	if comparison != "exact" && comparison != "unordered" {
		return "", nil, fmt.Errorf("%s: unknown comparison %q", problem, comparison)
	}
	fixtures, err := filepath.Rel(directory, filepath.Join(problem, "testcases.json"))
	if err != nil {
		return "", nil, err
	}
	adapter, err := renderAdapter(packageName, function, fixtures, comparison)
	return function.name, adapter, err
}

func findRoot() (string, error) {
	start, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for path := start; ; path = filepath.Dir(path) {
		if _, err := os.Stat(filepath.Join(path, "go.mod")); err == nil {
			return path, nil
		}
		if filepath.Dir(path) == path {
			return "", fmt.Errorf("run inside the leetcode repository")
		}
	}
}

func run(args []string) error {
	if len(args) == 0 || (args[0] != "test" && args[0] != "generate") {
		return fmt.Errorf("usage: go run ./cmd/leetcode <test|generate> [--function name] [--run pattern] [solution-or-problem-path]")
	}
	flags := flag.NewFlagSet(args[0], flag.ContinueOnError)
	selected := flags.String("function", "", "select an entry function when signatures are ambiguous")
	filter := flags.String("run", "", "Go test name filter")
	if err := flags.Parse(args[1:]); err != nil {
		return err
	}
	if flags.NArg() > 1 {
		return fmt.Errorf("supply at most one solution or problem directory")
	}
	root, err := findRoot()
	if err != nil {
		return err
	}
	target := filepath.Join(root, "problems", "algorithms")
	if flags.NArg() == 1 {
		target, err = filepath.Abs(flags.Arg(0))
		if err != nil {
			return err
		}
	}
	relative, err := filepath.Rel(filepath.Join(root, "problems", "algorithms"), target)
	if err != nil || relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) {
		return fmt.Errorf("target must be inside problems/algorithms")
	}
	var directories []string
	err = filepath.WalkDir(target, func(path string, file fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if !file.IsDir() && file.Name() == "solution.go" {
			rel, err := filepath.Rel(root, path)
			if err != nil {
				return err
			}
			if strings.Contains(filepath.ToSlash(rel), "/solutions/go/") {
				directories = append(directories, filepath.Dir(path))
			}
		}
		return nil
	})
	if err != nil {
		return err
	}
	if len(directories) == 0 {
		return fmt.Errorf("%s: no Go solutions found", target)
	}
	if *selected != "" && len(directories) != 1 {
		return fmt.Errorf("--function requires selecting one solution directory")
	}
	type generated struct {
		path    string
		content []byte
		name    string
	}
	var adapters []generated
	for _, directory := range directories {
		name, content, err := prepare(root, directory, *selected)
		if err != nil {
			return err
		}
		path := filepath.Join(directory, generatedName)
		if existing, err := os.ReadFile(path); err == nil {
			if !bytes.HasPrefix(existing, []byte(generatedHeader+"\n")) {
				return fmt.Errorf("refusing to overwrite handwritten file %s", path)
			}
		} else if !os.IsNotExist(err) {
			return err
		}
		adapters = append(adapters, generated{path, content, name})
	}
	packages := make([]string, len(directories))
	for index, adapter := range adapters {
		if err := os.WriteFile(adapter.path, adapter.content, 0644); err != nil {
			return err
		}
		rel, _ := filepath.Rel(root, directories[index])
		packages[index] = "./" + filepath.ToSlash(rel)
		fmt.Printf("Prepared %s (%s)\n", packages[index], adapter.name)
	}
	if args[0] == "generate" {
		return nil
	}
	testArgs := []string{"test", "-v", "-count=1", "-timeout=30s"}
	if *filter != "" {
		testArgs = append(testArgs, "-run", *filter)
	}
	testArgs = append(testArgs, packages...)
	command := exec.Command("go", testArgs...)
	command.Dir = root
	command.Stdout, command.Stderr = os.Stdout, os.Stderr
	return command.Run()
}

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, "leetcode:", err)
		os.Exit(1)
	}
}
